blank_issues_enabled: false
contact_links:
  - name: ğŸ—£ Ask a Question, Discuss
    url: https://github.com/anitrend/anitrend-anitrend-website/discussions
    about: General discussion, suggest ideas, share concepts or resources or ask questions, like "How does this work ğŸ¤”?"
  - name: ğŸ¤— Support the Project
    url: https://patreon.com/wax911
    about: Support the AniTrend financially.